### ISSUE TITLE
Request : Add services in User Service to allow for easy update of user information such as names, email, password.

### ISSUE THREAD

**Issue by superDeano** [twatter-soen341/Twatter#132]
## Description
Users want to be able to change their information. Routes and services allowing for the update of the user information in the database are therefore required. 

## Task Breakdown
- Have services create functions in order to update each of the user info.

**Comment by superDeano** [comment]
Or someone from the backend can also tell me what the url is and I'll work on it.

**Comment by a-paggabao** [comment]
I'll help you in Sprint 4 :)

**Comment by superDeano** [comment]
Thanks but then that'll mean i won't do anything for sprint 3?

**Comment by a-paggabao** [comment]
#### For User controller
`exports.updateUser = async (req, res, next) => {
  console.log('here');
  User.findByIdAndUpdate(req.params.id, 
    {$set: {
      firstName: req.body.firstName,
      lastName: req.body.lastName,
      following: req.body.following,
      followers: req.body.followers
    }}, 
    function (err) {
      if (err){
          res.status(500).json({message: 'Update Failed.', error: err});
      }
      else {
          res.status(200).json({message: 'User Updated'});
      }
  });
};`

#### For User route
`router.put('/users/:id', passport.authenticate('jwt', { session: false }), userController.updateUser);`

#### For settings.component.ts
To get logged user's id:
`ngOnInit() {
    this.userService.getCurrentUser().subscribe(user => {
      this.user = user;
    });
  }`

To update first name and last name:
`changeUserName() {
    this.user.firstName = this.changeForm.get('firstNameController').value;
    this.user.lastName = this.changeForm.get('lastNameController').value;
    console.log(this.user);
    this.userService.updateUserNames(this.user).subscribe(res => {
      console.log(res);
    });
  }`

For : `changeUserEmail() { } and changeUserPassword() { }`, 
it's similar, but you will use auth model and update AuthService instead of User.

#### For settings scss
import twatter-default-style.scss and change
`.title{
  color: rgb(192,24,91);
}`
to
`.title{
  color: mat-color($primary);
}`
So our theme is dynamic and will be easier to implement our potential theme feature.

**Comment by paulMoose** [comment]
removed the help wanted tag as it is used to attract outside contributors to our project.
https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels
